function oliotdiscoveryservice(){var T='',Bb='" for "gwt:onLoadErrorFn"',zb='" for "gwt:onPropertyErrorFn"',mb='"><\/script>',bb='#',lc='.cache.html',db='/',pb='//',ac='05D8EF3CCAA40A29F17155BC5ED98070',bc='0B4A8A2F4DE592B2B59628ADE813F143',cc='153E2B5879C152298C6C04A0DCEA83DB',dc='3E207AC3549C710D4D1CC0CDF44EA9E9',ec='4D993EFDDFF335B8E96CD76A3B158D82',fc='518728215BD24861577B8F700ED6218F',gc='877779FB47483016AB2BA6FF33AE1469',kc=':',tb='::',vc='<script defer="defer">oliotdiscoveryservice.onInjectionDone(\'oliotdiscoveryservice\')<\/script>',lb='<script id="',uc='<script language="javascript" src="http://maps.google.com/maps/api/js?sensor=false"><\/script>',wb='=',cb='?',hc='B251B970CD7FFCBE0A215F09FD1EB976',yb='Bad handler "',ic='DF04E3E2FB468321861ED1F83CCBD8E8',sc='DOMContentLoaded',jc='F2E6472824F11DD50E7A5E6658435DE5',Kb='Gears.Factory',nb='SCRIPT',kb='__gwt_marker_oliotdiscoveryservice',Mb='application/x-googlegears',ob='base',gb='baseUrl',X='begin',W='bootstrap',fb='clear.cache.gif',vb='content',ab='end',Hb='function',Jb='gears',Wb='gecko',Xb='gecko1_8',Gb='geolocation.api',Y='gwt.codesvr=',Z='gwt.hosted=',$='gwt.hybrid',mc='gwt/clean/clean.css',Ab='gwt:onLoadErrorFn',xb='gwt:onPropertyErrorFn',ub='gwt:property',rc='head',$b='hosted.html?oliotdiscoveryservice',qc='href',Ib='html5',tc='http://maps.google.com/maps/api/js?sensor=false',Tb='ie10',Vb='ie8',Ub='ie9',Lb='ie_mobile',Cb='iframe',eb='img',Db="javascript:''",nc='link',Zb='loadExternalRefs',qb='meta',Fb='moduleRequested',_='moduleStartup',Sb='msie',rb='name',Ob='none',Nb='object',U='oliotdiscoveryservice',ib='oliotdiscoveryservice.nocache.js',sb='oliotdiscoveryservice::',Eb='position:absolute;width:0;height:0;border:none',oc='rel',Rb='safari',hb='script',_b='selectingPermutation',V='startup',pc='stylesheet',jb='undefined',Yb='unknown',Pb='user.agent',Qb='webkit';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=T,u={},v=[],w=[],A=[],B=0,C,D;o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:X});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function F(){var b=false;try{var c=m.location.search;return (c.indexOf(Y)!=-1||(c.indexOf(Z)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf($)==-1}catch(a){}F=function(){return b};return b}
function G(){if(q&&r){var b=n.getElementById(U);var c=b.contentWindow;if(F()){c.__gwt_getProperty=function(a){return L(a)}}oliotdiscoveryservice=null;c.gwtOnLoad(C,U,t,B);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:_,millis:(new Date).getTime(),type:ab})}}
function H(){function e(a){var b=a.lastIndexOf(bb);if(b==-1){b=a.length}var c=a.indexOf(cb);if(c==-1){c=a.length}var d=a.lastIndexOf(db,Math.min(c,b));return d>=0?a.substring(0,d+1):T}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(eb);b.src=a+fb;a=e(b.src)}return a}
function g(){var a=J(gb);if(a!=null){return a}return T}
function h(){var a=n.getElementsByTagName(hb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(ib)!=-1){return e(a[b].src)}}return T}
function i(){var a;if(typeof isBodyLoaded==jb||!isBodyLoaded()){var b=kb;var c;n.write(lb+b+mb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=nb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return T}
function j(){var a=n.getElementsByTagName(ob);if(a.length>0){return a[a.length-1].href}return T}
function k(){var a=n.location;return a.href==a.protocol+pb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==T){l=h()}if(l==T){l=i()}if(l==T){l=j()}if(l==T&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function I(){var b=document.getElementsByTagName(qb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(rb),g;if(f){f=f.replace(sb,T);if(f.indexOf(tb)>=0){continue}if(f==ub){g=e.getAttribute(vb);if(g){var h,i=g.indexOf(wb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=T}u[f]=h}}else if(f==xb){g=e.getAttribute(vb);if(g){try{D=eval(g)}catch(a){alert(yb+g+zb)}}}else if(f==Ab){g=e.getAttribute(vb);if(g){try{C=eval(g)}catch(a){alert(yb+g+Bb)}}}}}}
function J(a){var b=u[a];return b==null?null:b}
function K(a,b){var c=A;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function L(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(D){D(a,d,b)}throw null}
var M;function N(){if(!M){M=true;var a=n.createElement(Cb);a.src=Db;a.id=U;a.style.cssText=Eb;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:_,millis:(new Date).getTime(),type:Fb});a.contentWindow.location.replace(t+P)}}
w[Gb]=function(){if(typeof navigator.geolocation!=jb&&typeof navigator.geolocation.getCurrentPosition==Hb){return Ib}if(window.google&&google.gears){return Jb}var b=null;if(typeof GearsFactory!=jb){b=new GearsFactory}else{try{b=new ActiveXObject(Kb);if(b.getBuildInfo().indexOf(Lb)!=-1){b.privateSetGlobalObject(this)}}catch(a){if(typeof navigator.mimeTypes!=jb&&navigator.mimeTypes[Mb]){b=document.createElement(Nb);b.style.display=Ob;b.width=0;b.height=0;b.type=Mb;document.documentElement.appendChild(b)}}}if(!b){return Ib}if(!window.google){google={}}if(!google.gears){google.gears={factory:b}}return Jb};v[Gb]={gears:0,html5:1};w[Pb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Qb)!=-1}())return Rb;if(function(){return b.indexOf(Sb)!=-1&&n.documentMode>=10}())return Tb;if(function(){return b.indexOf(Sb)!=-1&&n.documentMode>=9}())return Ub;if(function(){return b.indexOf(Sb)!=-1&&n.documentMode>=8}())return Vb;if(function(){return b.indexOf(Wb)!=-1}())return Xb;return Yb};v[Pb]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};oliotdiscoveryservice.onScriptLoad=function(){if(M){r=true;G()}};oliotdiscoveryservice.onInjectionDone=function(){q=true;o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:Zb,millis:(new Date).getTime(),type:ab});G()};I();H();var O;var P;if(F()){if(m.external&&(m.external.initModule&&m.external.initModule(U))){m.location.reload();return}P=$b;O=T}o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:_b});if(!F()){try{K([Jb,Vb],ac);K([Ib,Xb],bc);K([Ib,Rb],cc);K([Ib,Tb],dc);K([Ib,Vb],ec);K([Ib,Ub],fc);K([Jb,Ub],gc);K([Jb,Xb],hc);K([Jb,Rb],ic);K([Jb,Tb],jc);O=A[L(Gb)][L(Pb)];var Q=O.indexOf(kc);if(Q!=-1){B=Number(O.substring(Q+1));O=O.substring(0,Q)}P=O+lc}catch(a){return}}var R;function S(){if(!s){s=true;if(!__gwt_stylesLoaded[mc]){var a=n.createElement(nc);__gwt_stylesLoaded[mc]=a;a.setAttribute(oc,pc);a.setAttribute(qc,t+mc);n.getElementsByTagName(rc)[0].appendChild(a)}G();if(n.removeEventListener){n.removeEventListener(sc,S,false)}if(R){clearInterval(R)}}}
if(n.addEventListener){n.addEventListener(sc,function(){N();S()},false)}var R=setInterval(function(){if(/loaded|complete/.test(n.readyState)){N();S()}},50);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:ab});o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:Zb,millis:(new Date).getTime(),type:X});if(!__gwt_scriptsLoaded[tc]){__gwt_scriptsLoaded[tc]=true;document.write(uc)}n.write(vc)}
oliotdiscoveryservice();